version: "3.3"
services:
 postgres:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: default_database
    ports:
      - 15432:5432/tcp
    container_name: postgres
    networks:
      - db
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./config/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
    db:
        external: true